In [ ]:
#Name- Samir Sudhir Babar
#prn=123B1D007

#ass 2(b)
#scraping the web,scrapping the table,creating the dataframe to show scraped tables
#using panadas,html5lib,requests
#requests=read web
#html5lib=parse the data

In [ ]:
!pip install bs4;
!pip install html5lib;
!piop install request;

In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import html5lib

url="https://en.wikipedia.org/wiki/World_population"#importing url
cont=requests.get(url)#reading
samir=BeautifulSoup(cont.content,"html.parser")#parsing the distribute data
table1=samir.find('table',{"class":"wikitable sortable"})#finding the exact table location by using class,we can also do it by using id
#here wikipedia sortable is class of table
#print(table1) #herewe ce will get html code through
headers=table1.find_all("th")#here th means table heads(columnnames)
print(headers)

[<th scope="col">Region
</th>, <th scope="col">Density<br/><small>(inhabitants/km<sup>2</sup>)</small>
</th>, <th scope="col">Population<br/><small>(millions)</small>
</th>, <th scope="col">Most populous country
</th>, <th scope="col">Most populous city (metropolitan area)
</th>]

In [ ]:
#create dummy title array to save headers files data
titles=[]
for x in headers:
  title=x.text
  titles.append(title)#saving in a dummay array created over
print(titles)

['Region\n', 'Density(inhabitants/km2)\n', 'Population(millions)\n', 'Most populous country\n', 'Most populous city (metropolitan area)\n']

In [ ]:
#findinf data in arrays and using a dummur array
rows=table1.find_all('tr')#here tr means table rows
data=[]
for x in rows:
  row_data=x.find_all('td')#now we know rows of the table but dont kow the exact data in a tble so td is tabels data
  #print(data)
  # now here we are getting very disributed data so we are trying to do print data's element as text
  neetdata=[tr.text for tr in row_data]
  data.append(neetdata)#saving in dummy array created over
  print(neetdata)

[]
['Asia\n', '104.1\n', '4,641\n', '1,439,090,595 – \xa0India\n', '13,515,000 –  Tokyo Metropolis(37,400,000 –  Greater Tokyo Area)\n']
['Africa\n', '44.4\n', '1,340\n', '0,211,401,000 – \xa0Nigeria\n', '09,500,000 –  Cairo(20,076,000 –  Greater Cairo)\n']
['Europe\n', '73.4\n', '747\n', '0,146,171,000 – \xa0Russia, approx. 110\xa0million in Europe\n', '13,200,000 –  Moscow(20,004,000 –  Moscow metropolitan area)\n']
['Latin America\n', '24.1\n', '653\n', '0,214,103,000 – \xa0Brazil\n', '12,252,000 –  São Paulo City(21,650,000 –  São Paulo Metro Area)\n']
['Northern America[note 1]\n', '14.9\n', '368\n', '0,332,909,000 – \xa0United States\n', '08,804,000 –  New York City(23,582,649 –  New York metropolitan area[89])\n']
['Oceania\n', '5\n', '42\n', '0,025,917,000 – \xa0Australia\n', '05,367,000 –  Sydney\n']
['Antarctica\n', '~0\n', '0.004[87]\n', 'N/A[note 2]\n', '00,001,258 –  McMurdo Station\n']

In [ ]:
#now creating a dataframe
raju=pd.DataFrame(data,columns=titles)
raju

,Region\n,Density(inhabitants/km2)\n,Population(millions)\n,Most populous country\n,Most populous city (metropolitan area)\n
0,None,None,None,None,None
1,Asia\n,104.1\n,"4,641\n","1,439,090,595 – India\n","13,515,000 – Tokyo Metropolis(37,400,000 – G..."
2,Africa\n,44.4\n,"1,340\n","0,211,401,000 – Nigeria\n","09,500,000 – Cairo(20,076,000 – Greater Cair..."
3,Europe\n,73.4\n,747\n,"0,146,171,000 – Russia, approx. 110 million i...","13,200,000 – Moscow(20,004,000 – Moscow metr..."
4,Latin America\n,24.1\n,653\n,"0,214,103,000 – Brazil\n","12,252,000 – São Paulo City(21,650,000 – São..."
5,Northern America[note 1]\n,14.9\n,368\n,"0,332,909,000 – United States\n","08,804,000 – New York City(23,582,649 – New ..."
6,Oceania\n,5\n,42\n,"0,025,917,000 – Australia\n","05,367,000 – Sydney\n"
7,Antarctica\n,~0\n,0.004[87]\n,N/A[note 2]\n,"00,001,258 – McMurdo Station\n"